name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # https://doc.rust-lang.org/cargo/reference/profiles.html#release
  RUSTFLAGS: -Coverflow-checks=y -Cdebug-assertions=y
  # https://doc.rust-lang.org/cargo/reference/profiles.html#incremental
  CARGO_INCREMENTAL: 1
  # https://nexte.st/book/pre-built-binaries.html#using-nextest-in-github-actions
  CARGO_TERM_COLOR: always

jobs:
  run_checks:
    runs-on: ubuntu-latest
    name: Run some basic checks and tests
    steps:
      #
      # Setup
      #

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up cargo/rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # https://github.com/Swatinem/rust-cache
      - name: Cache Rust stuff
        uses: Swatinem/rust-cache@v1

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      #
      # Tests
      # 

      - name: Test with latest nextest release (faster than cargo test)
        run: cargo nextest run --all-features --release

      #
      # Coding guidelines
      #

      - name: Enforce formatting
        run: cargo fmt -- --check

      # - name: Lint (clippy)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --all-features -- -D warnings
